version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: sh -c "npm start"
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000
    networks:
      - fcnet
    depends_on:
      database:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - fcnet
    depends_on:
      - app

  database:
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password
    container_name: database
    restart: always
    tty: true
    volumes:  
      - ./mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fcnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 20s


networks:
  fcnet:
    driver: bridge

    
    

